# refer to https://app.koofr.net/links/90cbd5aa-ef70-4f5e-99bc-f12e5a89380e?path=%2F2021-04-03T19-39-50_cin_transformer%2Fconfigs%2F2021-04-03T19-39-50-project.yaml
seed_everything: true
trainer:
  accelerator: gpu
  strategy: ddp_find_unused_parameters_true
  devices: 8
  num_nodes: 1
  precision: 16-mixed
  max_epochs: 300
  check_val_every_n_epoch: 1
  num_sanity_val_steps: 0
  gradient_clip_val: 1.0
  callbacks:
    - class_path: lightning.pytorch.callbacks.ModelCheckpoint
      init_args:
        dirpath: "../../checkpoints/gq/test"
        save_top_k: 20
        monitor: "train/loss"
    - class_path: lightning.pytorch.callbacks.LearningRateMonitor
      init_args:
        logging_interval: step
  logger:
    class_path: lightning.pytorch.loggers.TensorBoardLogger
    init_args:
      save_dir: "../../results/gq/"
      version: "test"
      name:

model:
  class_path: src.IBQ.models.cond_transformer_llama.Net2NetTransformerPiT
  init_args:
    learning_rate: 3e-4
    first_stage_key: image
    cond_stage_key: class_label
    weight_decay: 5e-2
    wpe: 0.1 #learning rate decay
    wp: 6
    wp0: 0.005
    twde: 0
    ae_config: /workspace/cogview_dev/xutd/xu/pytorch-image-tokenizer/configs/sd3unet_gq_r_128_16_g_16.yaml
    ae_ckpt: /workspace/cogview_dev/xutd/xu/pytorch-image-tokenizer/models_128/gaussianquant.ckpt
    transformer_config:
      target: src.IBQ.modules.transformer.llama.GPT
      params:
        vocab_size: 65536
        block_size: 256
        n_layer: 16
        n_head: 16
        n_embd: 1024
        cond_dim: 1024
        resid_dropout_p: 0.1
        ffn_dropout_p: 0.1
        token_drop: 0.1
        drop_path_rate: 0.0 ##not using droppath rate
        alng: 1e-3
        class_num: 1000 #class tokens
    cond_stage_config:
      target: src.IBQ.modules.util.Labelator
      params:
        n_classes: 1000

data:
  class_path: main.DataModuleFromConfig
  init_args:
    batch_size: 64
    num_workers: 16
    train:
      target: src.IBQ.data.imagenet.ImageNetTrain
      params:
        config:
          size: 128
    validation:
      target: src.IBQ.data.imagenet.ImageNetValidation
      params:
        config:
          size: 128
          subset:
    test:
      target: src.IBQ.data.imagenet.ImageNetValidation
      params:
        config:
          size: 128
          subset:

ckpt_path: null # to resume